# Generated by Django 3.2.8 on 2021-11-24 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaToxicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('denominacion', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Categorias toxicológicas',
                'ordering': ('denominacion',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ('pais', 'departamento'),
            },
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanciaLinea', models.IntegerField()),
                ('distanciaPlanta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Distribuciones de las plantas',
                'ordering': ('distanciaLinea', 'distanciaPlanta'),
            },
        ),
        migrations.CreateModel(
            name='FaseCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faseCultivo', models.CharField(max_length=256)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fases de cultivo',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFinca', models.CharField(max_length=2048)),
                ('vereda', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Fincas',
                'ordering': ('nombreFinca',),
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hito', models.CharField(max_length=256)),
                ('duracionEstimada', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hitos',
                'ordering': ('hito',),
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInsumo', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'ordering': ('nombreInsumo',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ('pais',),
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(max_length=256)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Periodicidades',
                'ordering': ('periodicidad',),
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=15)),
                ('altura', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Posiciones globales (coordenadas)',
            },
        ),
        migrations.CreateModel(
            name='TipoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFertilizante', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Tipos de fertilizante',
                'ordering': ('tipoFertilizante',),
            },
        ),
        migrations.CreateModel(
            name='TipoFormulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('denominacion', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Tipos de formulación',
                'ordering': ('denominacion',),
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadMedida', models.CharField(max_length=256)),
                ('abreviatura', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ('unidadMedida',),
            },
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadTiempo', models.CharField(max_length=256)),
                ('minutos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Unidades de tiempo',
                'ordering': ('minutos',),
            },
        ),
        migrations.CreateModel(
            name='UsoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usoFertilizante', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Usos de fertilizante',
                'ordering': ('usoFertilizante',),
            },
        ),
        migrations.CreateModel(
            name='Agroquimico',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.insumo')),
                ('registroICA', models.IntegerField()),
                ('fechaRegistro', models.DateField()),
                ('empresa', models.CharField(max_length=2048)),
                ('categoriaToxico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.categoriatoxicologica')),
                ('tipoFormulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoformulacion')),
            ],
            options={
                'verbose_name_plural': 'Agroquímicos',
                'ordering': ('registroICA',),
            },
            bases=('modelos.insumo',),
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.insumo')),
                ('nombreSemilla', models.CharField(max_length=512)),
                ('fechaCompra', models.DateField()),
                ('proveedor', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Semillas',
                'ordering': ('nombreSemilla',),
            },
            bases=('modelos.insumo',),
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInsumo', models.CharField(max_length=256)),
                ('tipoInsumoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoinsumo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de insumo',
                'ordering': ('tipoInsumo',),
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCultivo', models.CharField(max_length=256)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.distribucion')),
            ],
            options={
                'verbose_name_plural': 'Tipos de cultivo',
                'ordering': ('tipoCultivo',),
            },
        ),
        migrations.CreateModel(
            name='TareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareaPlantilla', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=2048)),
                ('duracion', models.IntegerField(default=0)),
                ('inicioDesde', models.IntegerField(default=0)),
                ('plantasAfectadas', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('faseCultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.fasecultivo')),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.hito')),
                ('periodicidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='modelos.periodicidad')),
                ('unidadTiempo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadtiempo')),
            ],
            options={
                'verbose_name_plural': 'Plantillas de tareas para el cultivo',
                'ordering': ('orden', 'tareaPlantilla'),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuid', models.CharField(max_length=64, unique=True)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ('nuid',),
            },
        ),
        migrations.AddField(
            model_name='periodicidad',
            name='unidadTiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadtiempo'),
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('ruta', models.CharField(blank=True, max_length=256, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('opcion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.opcionmenu')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=512)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ('departamento', 'municipio'),
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaActualizacion', models.DateTimeField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.insumo')),
            ],
            options={
                'verbose_name_plural': 'Intentario',
            },
        ),
        migrations.CreateModel(
            name='InsumoTareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadInsumo', models.IntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.insumo')),
                ('tareaPlantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tareaplantilla')),
            ],
            options={
                'verbose_name_plural': 'Asignación de Insumos a Tareas',
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipoInsumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoinsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadmedida'),
        ),
        migrations.AddField(
            model_name='finca',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.municipio'),
        ),
        migrations.AddField(
            model_name='finca',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.posicion'),
        ),
        migrations.AddField(
            model_name='fasecultivo',
            name='tipoCultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipocultivo'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContrato', models.DateTimeField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.persona')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ('fechaContrato',),
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.pais'),
        ),
        migrations.CreateModel(
            name='Plaguicida',
            fields=[
                ('agroquimico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.agroquimico')),
                ('modificaciones', models.CharField(max_length=2048)),
                ('ingredienteActivo', models.CharField(max_length=512)),
                ('concentracion', models.CharField(max_length=512)),
                ('paisesOrigen', models.CharField(max_length=2048)),
                ('cultivos', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Plaguicidas',
            },
            bases=('modelos.agroquimico',),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.insumo')),
                ('fechaCompra', models.DateField()),
                ('periodoManteminiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.periodicidad')),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
            },
            bases=('modelos.insumo',),
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('agroquimico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.agroquimico')),
                ('tipoFertilizante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipofertilizante')),
                ('usoFertilizante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.usofertilizante')),
            ],
            options={
                'verbose_name_plural': 'Fertilizantes',
            },
            bases=('modelos.agroquimico',),
        ),
    ]
