# Generated by Django 3.2.8 on 2021-11-03 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaToxicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('denominacion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanciaLinea', models.IntegerField()),
                ('distanciaPlanta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPlanta', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FaseCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faseCultivo', models.CharField(max_length=256)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFinca', models.CharField(max_length=2048)),
                ('vereda', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInsumo', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('nombreInsumo',),
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaActualizacion', models.DateTimeField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(max_length=256)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('periodicidad',),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuid', models.CharField(max_length=64, unique=True)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nuid',),
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField(default=0)),
                ('consecutivo', models.IntegerField(default=0)),
                ('viva', models.BooleanField(default=True)),
                ('observaciones', models.CharField(max_length=2048)),
                ('ultimaActualizacion', models.DateTimeField(null=True)),
                ('estadoPlanta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.estadoplanta')),
            ],
            options={
                'ordering': ('linea', 'consecutivo'),
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=15)),
                ('altura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareaPlantilla', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=2048)),
                ('duracion', models.IntegerField(default=0)),
                ('jornalesHectarea', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('faseCultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.fasecultivo')),
                ('periodicidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='modelos.periodicidad')),
            ],
            options={
                'ordering': ('orden', 'tareaPlantilla'),
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCultivo', models.CharField(max_length=256)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.distribucion')),
            ],
            options={
                'ordering': ('tipoCultivo',),
            },
        ),
        migrations.CreateModel(
            name='TipoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFertilizante', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFormulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('denominacion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadMedida', models.CharField(max_length=256)),
                ('abreviatura', models.CharField(max_length=18)),
            ],
            options={
                'ordering': ('unidadMedida',),
            },
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadTiempo', models.CharField(max_length=256)),
                ('minutos', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('minutos',),
            },
        ),
        migrations.CreateModel(
            name='UsoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usoFertilizante', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Agroquimico',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.insumo')),
                ('registroICA', models.IntegerField()),
                ('fechaRegistro', models.DateField()),
                ('empresa', models.CharField(max_length=2048)),
                ('categoriaToxico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.categoriatoxicologica')),
                ('tipoFormulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoformulacion')),
            ],
            bases=('modelos.insumo',),
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('tipocultivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.tipocultivo')),
                ('fechaInicio', models.DateField()),
            ],
            bases=('modelos.tipocultivo',),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tareaplantilla_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.tareaplantilla')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('finalizada', models.BooleanField(default=False)),
            ],
            bases=('modelos.tareaplantilla',),
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInsumo', models.CharField(max_length=256)),
                ('tipoInsumoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoinsumo')),
            ],
            options={
                'ordering': ('tipoInsumo',),
            },
        ),
        migrations.AddField(
            model_name='tareaplantilla',
            name='unidadTiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadtiempo'),
        ),
        migrations.AddField(
            model_name='periodicidad',
            name='unidadTiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadtiempo'),
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('ruta', models.CharField(blank=True, max_length=256, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('opcion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.opcionmenu')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=512)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoTareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadInsumo', models.IntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.insumo')),
                ('tareaPlantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tareaplantilla')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipoInsumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipoinsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadmedida'),
        ),
        migrations.AddField(
            model_name='finca',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.municipio'),
        ),
        migrations.AddField(
            model_name='finca',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.posicion'),
        ),
        migrations.AddField(
            model_name='fasecultivo',
            name='tipoCultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipocultivo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.pais'),
        ),
        migrations.CreateModel(
            name='Plaguicida',
            fields=[
                ('agroquimico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.agroquimico')),
                ('modificaciones', models.CharField(max_length=2048)),
                ('ingredienteActivo', models.CharField(max_length=512)),
                ('cencentracion', models.CharField(max_length=512)),
                ('paisesOrigen', models.CharField(max_length=2048)),
                ('cultivos', models.CharField(max_length=2048)),
            ],
            bases=('modelos.agroquimico',),
        ),
        migrations.CreateModel(
            name='TareaPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False)),
                ('fechaRealizada', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(max_length=2048)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.planta')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidadUsada', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.inventario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.cultivo'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('insumo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.insumo')),
                ('tmanteminiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.usofertilizante')),
            ],
            bases=('modelos.insumo',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.persona')),
                ('fechaContrato', models.DateTimeField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
            ],
            bases=('modelos.persona',),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.empleado')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tarea')),
            ],
            bases=('modelos.empleado',),
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('agroquimico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelos.agroquimico')),
                ('tipoFertilizante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tipofertilizante')),
                ('usoFertilizante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.usofertilizante')),
            ],
            bases=('modelos.agroquimico',),
        ),
    ]
