# Generated by Django 3.2.8 on 2021-11-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agroquimico',
            options={'ordering': ('registroICA',), 'verbose_name_plural': 'Inventario - 03 Agroquímicos'},
        ),
        migrations.AlterModelOptions(
            name='categoriatoxicologica',
            options={'ordering': ('denominacion',), 'verbose_name_plural': 'Inventario - 02 Categorias toxicológicas'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('pais', 'departamento'), 'verbose_name_plural': 'Utilitarias - 02 Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='distribucion',
            options={'ordering': ('distanciaLinea', 'distanciaPlanta'), 'verbose_name_plural': 'Plantilla tareas - 03 Distribuciones de las plantas'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('fechaContrato',), 'verbose_name_plural': 'RRHH - 01 Empleados'},
        ),
        migrations.AlterModelOptions(
            name='fasecultivo',
            options={'ordering': ('orden',), 'verbose_name_plural': 'Plantilla tareas - 05 Fases de cultivo'},
        ),
        migrations.AlterModelOptions(
            name='fertilizante',
            options={'verbose_name_plural': 'Inventario - 06 Fertilizantes'},
        ),
        migrations.AlterModelOptions(
            name='finca',
            options={'ordering': ('nombreFinca',), 'verbose_name_plural': 'Predio - Fincas'},
        ),
        migrations.AlterModelOptions(
            name='herramienta',
            options={'verbose_name_plural': 'Inventario - 08 Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='hito',
            options={'ordering': ('hito',), 'verbose_name_plural': 'Plantilla tareas - 06 Hitos'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ('nombreInsumo',), 'verbose_name_plural': 'Plantilla tareas - 02 Insumos'},
        ),
        migrations.AlterModelOptions(
            name='insumotareaplantilla',
            options={'verbose_name_plural': 'Plantilla tareas - 08 Asignación de Insumos a Tareas'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name_plural': 'Inventario - 10 Intentario'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ('departamento', 'municipio'), 'verbose_name_plural': 'Utilitarias - 03 Municipios'},
        ),
        migrations.AlterModelOptions(
            name='opcionmenu',
            options={'ordering': ('label',), 'verbose_name_plural': 'Principal - Menú'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('pais',), 'verbose_name_plural': 'Utilitarias - 01 Paises'},
        ),
        migrations.AlterModelOptions(
            name='periodicidad',
            options={'ordering': ('periodicidad',), 'verbose_name_plural': 'Utilitarias - 07 Periodicidades'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('nuid',), 'verbose_name_plural': 'Principal - Personas'},
        ),
        migrations.AlterModelOptions(
            name='plaguicida',
            options={'verbose_name_plural': 'Inventario - 07 Plaguicidas'},
        ),
        migrations.AlterModelOptions(
            name='posicion',
            options={'verbose_name_plural': 'Utilitarias - 04 Posiciones globales (coordenadas)'},
        ),
        migrations.AlterModelOptions(
            name='semilla',
            options={'ordering': ('nombreSemilla',), 'verbose_name_plural': 'Inventario - 09 Semillas'},
        ),
        migrations.AlterModelOptions(
            name='tareaplantilla',
            options={'ordering': ('orden', 'tareaPlantilla'), 'verbose_name_plural': 'Plantilla tareas - 07 Plantillas de tareas para el cultivo'},
        ),
        migrations.AlterModelOptions(
            name='tipocultivo',
            options={'ordering': ('tipoCultivo',), 'verbose_name_plural': 'Plantilla tareas - 04 Tipos de cultivo'},
        ),
        migrations.AlterModelOptions(
            name='tipofertilizante',
            options={'ordering': ('tipoFertilizante',), 'verbose_name_plural': 'Inventario - 04 Tipos de fertilizante'},
        ),
        migrations.AlterModelOptions(
            name='tipoformulacion',
            options={'ordering': ('denominacion',), 'verbose_name_plural': 'Inventario - 01 Tipos de formulación'},
        ),
        migrations.AlterModelOptions(
            name='tipoinsumo',
            options={'ordering': ('tipoInsumo',), 'verbose_name_plural': 'Plantilla tareas - 01 Tipos de insumo'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ('unidadMedida',), 'verbose_name_plural': 'Utilitarias - 05 Unidades de medida'},
        ),
        migrations.AlterModelOptions(
            name='unidadtiempo',
            options={'ordering': ('minutos',), 'verbose_name_plural': 'Utilitarias - 06 Unidades de tiempo'},
        ),
        migrations.AlterModelOptions(
            name='usofertilizante',
            options={'ordering': ('usoFertilizante',), 'verbose_name_plural': 'Inventario - 05 Usos de fertilizante'},
        ),
        migrations.AddField(
            model_name='hito',
            name='unidadTiempo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='modelos.unidadtiempo'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='latitud',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='longitud',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
