# Generated by Django 3.2.8 on 2021-12-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20211201_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoplanta',
            options={'ordering': ('nivel',), 'verbose_name_plural': 'Cultivo - 02 Estados planta'},
        ),
        migrations.AlterModelOptions(
            name='estadoplantaobservacion',
            options={'ordering': ('fecha',), 'verbose_name_plural': 'Cultivo - 03 Estados de la planta'},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('cultivo', 'linea', 'consecutivo', 'fechaSiembra'), 'verbose_name_plural': 'Cultivo - 02 Plantas'},
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('observacion', models.CharField(max_length=64)),
                ('plantas', models.ManyToManyField(to='modelos.Planta')),
                ('responsables', models.ManyToManyField(to='modelos.Empleado')),
                ('tareaPlantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.tareaplantilla')),
            ],
            options={
                'verbose_name_plural': 'Cultivo - 04 Tareas',
                'ordering': ('fechaInicial',),
            },
        ),
    ]
