# Generated by Django 3.2.8 on 2021-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_auto_20211206_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaplantilla',
            name='esMIPE',
            field=models.BooleanField(default=False),
        ),
    ]
