# Generated by Django 3.2.8 on 2021-12-06 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_tareaplantilla_esmipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('textoCriterio', models.CharField(max_length=2048)),
                ('criterioPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.criterio')),
            ],
            options={
                'verbose_name_plural': 'Norma ICA - 02 Criterio',
                'ordering': ('criterioPadre', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='NivelCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=64)),
                ('abreviatura', models.CharField(max_length=8)),
                ('porcentajeMin', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Norma ICA - 01 Nivel criterio',
                'ordering': ('nivel',),
            },
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='observacion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='CriterioFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheroSoporte', models.FileField(blank=True, null=True, upload_to='')),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaCaduca', models.DateTimeField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.criterio')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
                ('linkSoporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.opcionmenu')),
            ],
            options={
                'verbose_name_plural': 'Criterios de norma 30021 de 2017 - ICA',
                'ordering': ('finca', 'criterio'),
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='criterios',
            field=models.ManyToManyField(blank=True, through='modelos.CriterioFinca', to='modelos.Criterio'),
        ),
    ]
