# Generated by Django 3.2.8 on 2021-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_auto_20211206_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterio',
            options={'ordering': ('numero',), 'verbose_name_plural': 'Norma ICA - 02 Criterio'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='numero',
            field=models.CharField(max_length=32),
        ),
    ]
