# Generated by Django 3.2.8 on 2021-12-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_auto_20211206_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriofinca',
            name='criterio',
        ),
        migrations.RemoveField(
            model_name='criteriofinca',
            name='finca',
        ),
        migrations.RemoveField(
            model_name='criteriofinca',
            name='linkSoporte',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='criterios',
        ),
        migrations.DeleteModel(
            name='Criterio',
        ),
        migrations.DeleteModel(
            name='CriterioFinca',
        ),
    ]
