# Generated by Django 3.2.8 on 2021-12-06 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_auto_20211206_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32)),
                ('textoCriterio', models.CharField(max_length=2048)),
                ('criterioPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.criterio')),
                ('nivelCriterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.nivelcriterio')),
            ],
            options={
                'verbose_name_plural': 'Norma ICA - 02 Criterio',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='CriterioFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheroSoporte', models.FileField(blank=True, null=True, upload_to='')),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaCaduca', models.DateTimeField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.criterio')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.finca')),
                ('linkSoporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.opcionmenu')),
            ],
            options={
                'verbose_name_plural': 'Criterios de norma 30021 de 2017 - ICA',
                'ordering': ('finca', 'criterio'),
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='criterios',
            field=models.ManyToManyField(blank=True, through='modelos.CriterioFinca', to='modelos.Criterio'),
        ),
    ]
